# Generated by Django 2.0.4 on 2018-07-07 08:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='time',
            field=models.DateField(default=datetime.datetime(2018, 7, 7, 16, 26, 32, 88701)),
        ),
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='login',
            name='pwd',
            field=models.CharField(max_length=12),
        ),
    ]
