# Generated by Django 2.0.4 on 2018-07-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180707_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='time',
        ),
    ]
